Update xstar-tools to v0.6.90.5.1

diff --git a/docs/sphinx/Makefile b/docs/sphinx/Makefile
--- a/docs/sphinx/Makefile
+++ b/docs/sphinx/Makefile
@@ -12,9 +12,14 @@ html:
 
 latex:
 	@$(SPHINXBUILD) -W --keep-going -b latex "$(SOURCEDIR)" "$(BUILDDIR)/latex"
+	@for image in backend_dispatch local_zone_solve controller_radial_flow publication_ownership; do \
+		grep -q "$$image.eps" "$(BUILDDIR)/latex/xstar-tools.tex" || { \
+			echo "ERROR: LaTeX output does not reference $$image.eps" >&2; exit 1; \
+		}; \
+	done
 
 latexpdf:
-	@$(SPHINXBUILD) -W --keep-going -M latexpdf "$(SOURCEDIR)" "$(BUILDDIR)"
+	@$(SPHINXBUILD) -M latexpdf "$(SOURCEDIR)" "$(BUILDDIR)" -W --keep-going
 
 linkcheck:
 	@$(SPHINXBUILD) -W --keep-going -b linkcheck "$(SOURCEDIR)" "$(BUILDDIR)/linkcheck"
